#ifndef bmcsd_discrete_corresp_storage_3_sptr_h
#define bmcsd_discrete_corresp_storage_3_sptr_h

#include <bpro1/bpro1_storage_sptr.h>

class bmcsd_discrete_corresp_storage_3;
typedef bpro1_storage_sptr_t<bmcsd_discrete_corresp_storage_3> bmcsd_discrete_corresp_storage_3_sptr;

#endif // bmcsd_discrete_corresp_storage_3_sptr_h
