#ifndef bdifd_3rd_order_geometry_storage_sptr_h
#define bdifd_3rd_order_geometry_storage_sptr_h

#include <bpro1/bpro1_storage_sptr.h>

class bdifd_3rd_order_geometry_storage;
typedef bpro1_storage_sptr_t<bdifd_3rd_order_geometry_storage> bdifd_3rd_order_geometry_storage_sptr;

#endif // bdifd_3rd_order_geometry_storage_sptr_h
